#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    selector,       sensorPotentiometer)
#pragma config(Sensor, in4,    notworking,     sensorGyro)
#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_mm)
#pragma config(Sensor, dgtl11, leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           descorer,      tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           puncher1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightBack,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           intake,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           rightFront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           leftBack,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           puncher2,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
//-----------------------------------------------------------------------------

//Tasks/Functions/Gyro section

void BasicDrive(int left, int right, int revs)
{
	SensorValue[leftEncoder] = 0;

	while(abs(SensorValue[leftEncoder]) < revs)
	{
		if(abs(SensorValue[leftEncoder]) <= revs)
		{
			motor(rightBack) = motor(rightFront) = right;
			motor(leftBack) = motor(leftFront) = left;
		}
		else
		{
			motor(rightBack) = motor(rightFront) = 0;
			motor(leftBack) = motor(leftFront) = 0;
		}
	}
	motor(rightBack) = motor(rightFront) = 0;
	motor(leftBack) = motor(leftFront) = 0;
}

void WallDrive(int left, int right, int dist)
{

	while((SensorValue[sonar]) > dist)
	{
			motor(rightBack) = motor(rightFront) = right;
			motor(leftBack) = motor(leftFront) = left;
	}
	motor(rightBack) = motor(rightFront) = 0;
	motor(leftBack) = motor(leftFront) = 0;
}

void turn(int left, int right, int degrees10)
{
	SensorValue[gyro] = 0;
	while(abs(SensorValue[gyro]) < degrees10 - 10)
	{
		motor(leftBack) = motor(leftFront) = left;
		motor(rightBack) = motor(rightFront) = right;
	}
	//Brief brake to eliminate some drift
	if (left > 0)
	{
		motor[rightFront] = motor(rightBack) = -10;
		motor[leftFront] = motor(leftBack) = 10;
		wait1Msec(100);
	}
	else
	{
		motor[rightFront] = motor(rightBack) = 10;
		motor[leftFront] = motor(leftBack) = -10;
		wait1Msec(100);
	}
	//Stop
	motor[rightFront] = motor(rightBack) = 0;
	motor[leftFront] = motor(leftBack) = 0;
	wait1Msec(250);
}

//int error;


void LoopyMove (int power, int setpoint)
{
	SensorValue[leftEncoder] = 0;
	int kP = 0.5;
	while(abs(SensorValue[leftEncoder]) < setpoint)
	{
		motor(leftBack) = motor(leftFront) = (setpoint - SensorValue[leftEncoder]) * kP;
		motor(rightFront) = motor(rightFront) = (setpoint - SensorValue[leftEncoder]) * kP;
	}
	motor(rightBack) = motor(rightFront) = 0;
	motor(leftBack) = motor(leftFront) = 0;
}

int autoNumber;


task progselect()
{
	while (true)
	{
		if (SensorValue[selector] <= 1500) //when you go back use 400 for this one
		{
			autoNumber = 1;
		}
		//else if (SensorValue[selector] < 1150 && SensorValue[selector] > 400)
		//{
		//	autoNumber = 2;
		//}
		else if (SensorValue[selector] < 1550 && SensorValue[selector] > 1500) //when you go back use 1150 for this one
		{
			autoNumber = 3;
		}
		//else if (SensorValue[selector] < 2000 && SensorValue[selector] > 1550)
		//{
		//	autoNumber = 4;
		//}
		//else if (SensorValue[selector] < 2500 && SensorValue[selector] > 2000)
		//{
		//	autoNumber = 5;
		//}
		//else if (SensorValue[selector] < 3000 && SensorValue[selector] > 2500)
		//{
		//	autoNumber = 6;
		//}
		//else if (SensorValue[selector] < 3500 && SensorValue[selector] > 3000)
		//{
		//	autoNumber = 7;
		//}
		else
		{
			autoNumber = 3;
		}


		// give up the CPU, even though we may have
		// nothing else running in pre-autonomous
		wait1Msec(10);

		if (autoNumber == 1)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "Red Super");
			wait1Msec(100);
		}
		else if (autoNumber == 2)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "Red Far");
			wait1Msec(100);
		}
		else if (autoNumber == 3)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "Blue Super");
			wait1Msec(100);
		}
		else if (autoNumber == 4)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "Blue Far");
			wait1Msec(100);
		}
		else if (autoNumber == 5)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "3 Cone Block R");
			wait1Msec(100);
		}
		else if (autoNumber == 6)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "3 Cone Block L");
			wait1Msec(100);
		}
		else if (autoNumber == 7)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "Sationary");
			wait1Msec(100);
		}
		else if(autoNumber == 8)
		{
			displayLCDCenteredString(0, "Auton Selected: ");
			displayLCDCenteredString(1, "Mogo Hoard");
			wait1Msec(100);
		}
		else
		{
			wait1Msec(10);
		}
	}
}


void pre_auton()
{
	SensorValue(gyro)=0;
	startTask(progselect);
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
	SensorType[in2] = sensorNone;
	wait1Msec(1000);
	//Reconfigure Analog Port 2 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in2] = sensorGyro;
	wait1Msec(2000);



	bDisplayCompetitionStatusOnLcd = false;
	bLCDBacklight = true;
	clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
	clearLCDLine(1);                                            // Clear line 2 (1) of the LCD




	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.




}

task autonomous()
{
	SensorValue(gyro)=0;
	LoopyMove(0,0);
	stopTask(progselect);
	displayLCDCenteredString(0, "Starting Auton: ");
	if (autoNumber == 1) //red close/super
	{
	motor(intake) = 127;
	BasicDrive(127,127,800);
	BasicDrive(40, 40, 90);
	wait1Msec(900);
	//drive to tilted cap
	//take ball from tilted cap
	motor(intake) = 0;
	BasicDrive(-127, -127, 700);
	BasicDrive(-31, -31, 200);
	//drive back to wall
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = -31;
	wait1Msec(500);
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = -20;
	wait1Msec(500);
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 0;
	BasicDrive(31, 31, 100);
	wait1Msec(100);
	//turn to line up
	SensorValue(gyro)=0;
	turn(-31,31,625);
	//forward and shoot
	WallDrive(40,40,945);
			motor(rightBack) = motor(rightFront) = -10;
			motor(leftBack) = motor(leftFront) = -10;
			wait1Msec(100);
			motor(rightBack) = motor(rightFront) = 0;
			motor(leftBack) = motor(leftFront) = 0;
	motor(puncher1) = 127;
	motor(puncher2) = 127;
	wait1Msec(900);
	motor(puncher1) = 0;
	motor(puncher2) = 0;
	//forward and shoot
	SensorValue(gyro)=0;
	BasicDrive(40,40,475);
			motor(rightBack) = motor(rightFront) = -10;
			motor(leftBack) = motor(leftFront) = -10;
			wait1Msec(100);
			motor(rightBack) = motor(rightFront) = 0;
			motor(leftBack) = motor(leftFront) = 0;
	turn(31,-31,5);
	motor(intake) = 127;
	wait1Msec(1500); //little wait for ball to cycle
	motor(puncher1) = 127;
	motor(puncher2) = 127;
	wait1Msec(900);
	motor(puncher1) = 0;
	motor(puncher2) = 0;
	//slight turn
	SensorValue(gyro)=0;
	turn(-40, 40, 50);
	//low flag bop
	motor(descorer) = 80;
	wait1Msec(225);
	motor(descorer) = 0;
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 63;
	wait1Msec(350);
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 0;
	wait1Msec(400);
	//back away from flags
	BasicDrive(-63, -63, 300);
	motor(descorer) = -63;
	SensorValue(gyro)=0;
	turn(40, -40, 875);
	motor(descorer) = 0;
	motor(intake) = -127;
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 127;
	wait1Msec(600);
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 0;
	wait1Msec(200);
	BasicDrive(-63, -63, 100);


	}
	else if (autoNumber == 2) //red far
	{
		//shoot preload
		//turn and line up
		//drive to tiled cap
		//take the ball
		//back up
		//line up on platform
		//park
	}
	else if (autoNumber == 3) //blue super
	{
		SensorValue(gyro)=0;
		motor(intake) = 127;
	BasicDrive(127,127,800);
	BasicDrive(40, 40, 90);
	wait1Msec(900);
	motor(intake) = 0;
	//drive to tilted cap
	//take ball from tilted cap
	BasicDrive(-127, -127, 700);
	BasicDrive(-31, -31, 200);
	//drive back to wall
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = -31;
	wait1Msec(500);
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = -10;
	wait1Msec(600);
	BasicDrive(31, 31, 40);
	wait1Msec(100);
	//turn to line up
	SensorValue(gyro)=0;
	turn(31,-31,630);
	//forward and shoot
	WallDrive(31,31,1080);
			motor(rightBack) = motor(rightFront) = -10;
			motor(leftBack) = motor(leftFront) = -10;
			wait1Msec(100);
			motor(rightBack) = motor(rightFront) = 0;
			motor(leftBack) = motor(leftFront) = 0;
	motor(puncher1) = 127;
	motor(puncher2) = 127;
	wait1Msec(900);
	motor(puncher1) = 0;
	motor(puncher2) = 0;

	//forward and shoot
	BasicDrive(40,40,450);
			motor(rightBack) = motor(rightFront) = -10;
			motor(leftBack) = motor(leftFront) = -10;
			wait1Msec(100);
			motor(rightBack) = motor(rightFront) = 0;
			motor(leftBack) = motor(leftFront) = 0;
	turn(31, -31, 10);
	motor(intake) = 127;
	wait1Msec(1500); //little wait for ball to cycle
	motor(puncher1) = 127;
	motor(puncher2) = 127;
	wait1Msec(1200);
	motor(puncher1) = 0;
	motor(puncher2) = 0;
	//low flag bop
	SensorValue(gyro)=0;
	turn(-40, 40, 90);
	motor(descorer) = 80;
	wait1Msec(250);
	motor(descorer) = 0;
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 63;
	wait1Msec(525);
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 0;
	wait1Msec(400);
	motor(descorer) = -63;
	BasicDrive(-63, -63, 175);
	motor(descorer) = 0;
	SensorValue(gyro)=0;
	turn(-40, 40, 450);
	motor(intake) = -127;
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 127;
	wait1Msec(800);
	motor(leftBack) = motor(leftFront) = motor(rightBack) = motor(rightFront) = 0;
	wait1Msec(200);
	BasicDrive(-63, -63, 100);
	}
	else if (autoNumber == 4) //blue far
	{
		//shoot preload
		//turn and line up
		//drive to tiled cap
		//take the ball
		//back up
		//line up on platform
		//park
	}
	else
	{
		wait1Msec(10);
	}


}
task usercontrol()
{


	while (true)
	{
//thanks to jpearman for helping us when our drivercontrol was acting funky
    short   forward, turn;
    long    drive_l_front;
    long    drive_l_back;
    long    drive_r_front;
    long    drive_r_back;

    // Get controller, Arcade drive using Ch3 and Ch1
    if( abs( vexRT[ Ch3 ] ) > 10 )
        forward = vexRT[ Ch3 ];
    else
        forward = 0;

    if( abs( vexRT[ Ch1 ] ) > 10 )
        turn   = vexRT[ Ch1 ];
    else
        turn = 0;

    // Set drive variables
    drive_l_front = forward + turn;
    drive_l_back  = forward + turn;

    drive_r_front = forward - turn;
    drive_r_back  = forward - turn;


    // Send to motors
    // left drive
    motor[ leftFront ] =  drive_l_front;
    motor[ leftBack ] =  drive_l_back;

    // right drive
    motor[ rightFront ] =  drive_r_front;
    motor[ rightBack ] =  drive_r_back;
    //-------------------------------------------

		//launcher buttons
		if((vexRT[Btn5U] == 1))
		{
			motor(puncher1) = 127;
			motor(puncher2) = 127;
		}
		else
		{
			motor[puncher1] = 0;
			motor[puncher2] = 0;
		}
		//--------------------------------------------------------------------------------
		//Descorer Buttons
		if (vexRT[Btn6U] == 1)
		{
			motor(descorer) = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor(descorer) = 127;
		}
		else
		{
			motor(descorer) = 0;
		}






		//---------------------------------------------------------------------------------
		//Intake Buttons
		if (vexRT[Btn5D] == 1)
		{
			motor(intake) = 127;
		}
		else if(vexRT[Btn8U] == 1)
		{
			motor(intake) = -127;
		}
		else
		{
			motor(intake) = 0;
		}
	}
}	//this is the end
